### ISSUE TITLE
 object has no attribute key 

### ISSUE THREAD

**Issue by markvandenberg** [opstree/redis-load-test#2]
Hi,

We are using your code to run a redis load test but see an error.
task_set  object has no attribute key

Any suggestions? 

Mark

**Comment by giwery** [comment]
The same error

**Comment by iamabhishek-dubey** [comment]
I think I will fix this break by 16th September.

**Comment by iamabhishek-dubey** [comment]
The bug is fixed now, please see https://github.com/opstree/redis-load-test/pull/3 
![image](https://user-images.githubusercontent.com/26764731/64921641-44016180-d7e3-11e9-9235-1f39c0866221.png)
